### PR TITLE
Attempt osx build

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @seanyen @j-rivero
This PR adds osx support. The Windows build fails for unrelated reasons; it would be great if you could check why that is.
It would be great if this PR could be merged so we can get Gazebo on osx.

Many thanks!

**Comment by Tobias-Fischer** [comment]
Hacked the Windows build in https://github.com/conda-forge/libsdformat-feedstock/pull/8/commits/7cc4d4911821a0d34eca6cefbd7db2b2d4b3a061

Seems like Ruby is missing in newer build setups.

It would be great if you could merge this PR :)

**Comment by wolfv** [comment]
@Tobias-Fischer if it's Ruby that's missing, wouldn't it be better to install it with conda?

**Comment by wolfv** [comment]
ok apparently there is no ruby package for win...

**Comment by Tobias-Fischer** [comment]
Yeah .. not sure why Ruby was removed from https://github.com/conda-forge/conda-forge-ci-setup-feedstock

**Comment by Tobias-Fischer** [comment]
The hack does not seem to work: "Distribution D:\bld\win-64\libsdformat-9.1.0-h7dee32a_3.tar.bz2 is new for conda-forge, but no upload is taking place because the BINSTAR_TOKEN is missing."

Will wait for https://github.com/conda-forge/ruby-feedstock/issues/38 I guess ..

**Comment by seanyen** [comment]
@Tobias-Fischer I think you can skip the Windows build for this release. The `Ruby` thing looks little more complicated and I anticipated it might take longer runway to tackle it. I don't want this to be a blocker Gazebo on MacOS enablement. :)

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by seanyen** [comment]
LGTM.

**Pull request merged**
