### PR TITLE
Stop supporting v11

### PR DESCRIPTION
**Pull request by traversaro**
It just reached end of life, see https://github.com/ignition-tooling/release-tools/issues/655 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This is still being used in robostack. Do we know if ROS supports newer versions without issues?

**Comment by traversaro** [comment]
> This is still being used in robostack. Do we know if ROS supports newer versions without issues?

Interesting, I had no idea. The original repo is using sdformat9 (the one used in Gazebo Classic) , any idea why we patch it to use sdformat11 in https://github.com/RoboStack/ros-galactic/blob/9a8356042c270b69f77f2d8ef341ed807d3e5ea4/patch/ros-galactic-sdformat-urdf.patch instead?

**Comment by Tobias-Fischer** [comment]
I think because the ignition libraries that are pulled in (https://github.com/RoboStack/ros-noetic/blob/e5a20fca7f3882c9713460ab593d8ba826abc6ee/conda.yaml#L140-L159) only work with sdformat11?!? But I could be totally wrong.

**Comment by traversaro** [comment]
@Tobias-Fischer I guess we can go on with this now that all the effort on robostack has been moved to humble, right?

**Comment by Tobias-Fischer** [comment]
Hmmm, ideally we would like to support Noetic for a little while - this is a big attraction of RoboStack. I’m not sure if we can move Noetic to newer versions though?

**Pull request closed without merging**
