### PR TITLE
Enable Windows

### LINKED ISSUE #9: Fix Windows builds
Issue:
After Ruby has been removed from the Windows CI (see https://github.com/conda-forge/conda-forge-ci-setup-feedstock/issues/103#issuecomment-635515749), the Windows builds fail (see https://github.com/conda-forge/libsdformat-feedstock/pull/8). A conda Ruby build does not seem to be appearing any time soon (https://github.com/conda-forge/ruby-feedstock/pull/30).

Options:
- No Windows builds for a while
- Pushing https://github.com/conda-forge/ruby-feedstock/pull/30 forward
- Putting the Azure Ruby back in the path (ideally separately from the other pre-installed stuff which might interfere)

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fix #9 

Thanks @wolfv

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Shall we merge this now or wait until https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/908 is merged?

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
I think this is good to merge (I just rerendered) @conda-forge/libsdformat 

We can remove the pin on Ruby later, so we don't have to wait for https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/908

**Comment by wolfv** [comment]
Really happy that ruby works! :)

**Pull request merged**
